#!/bin/bash

# Variables
dir=~/dot_lin                     # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory

# Archive old dotfiles
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# Variables
dir=~/dot_lin                 # dotfiles directory

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $(ls); do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$file ~/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done
=======

# Create symlinks for all files in the directory
for file in $(ls); do
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done
rm ~/.README.md
rm ~/.setup 

# Download git plugins
git -C ~/dot_lin/vim/bundle/ clone https://github.com/Raimondi/delimitMate
git -C ~/dot_lin/vim/bundle/ clone https://github.com/ajh17/VimCompletesMe
