#!/bin/bash

GREEN="\033[1;32m"
ENDCOLOR="\e[0m"

echo -ne $GREEN">>> "$ENDCOLOR; echo "Registering key & feed..."
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/debian/10/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-dotnet.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list

echo -ne $GREEN">>> "$ENDCOLOR; echo "Installing .NET SDK"
sudo apt update -y
sudo apt install -y dotnet-sdk-2.2
