#!/bin/bash

GREEN="\033[1;32m"
ENDCOLOR="\e[0m"

echo -ne $GREEN">>> "$ENDCOLOR; echo "Installing Python 3"
sudo apt update -y
sudo apt install -y python3 python3-setuptools python3-dev build-essential python3-pip python3-venv

echo -ne $GREEN">>> "$ENDCOLOR; echo "Updating Pip packages"
pip3 install --upgrade pip
pip3 install --upgrade pipenv
pip3 install --upgrade pylint
pip3 install --upgrade prettytable
