#!/bin/bash

GREEN="\033[1;32m"
ENDCOLOR="\e[0m"

echo -ne $GREEN">>> "$ENDCOLOR; echo "Getting Dependancies"
# Install system components
sudo apt update -y 
sudo apt install -y curl gnupg apt-transport-https

echo -ne $GREEN">>> "$ENDCOLOR; echo "Registering key & feed..."
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'

echo -ne $GREEN">>> "$ENDCOLOR; echo "Installing Powershell"
sudo apt update -y
sudo apt install -y powershell


