#!/bin/bash
sudo apt install flameshot

# Free the printscreen key
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot '[]'

# Try and set up keybinding manually
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'flameshot'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/flameshot gui'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'Print'

echo Next steps:
echo  * Go to Settings -> Devices -> Keyboard and scroll to the end. Press + and you will
echo    create custom shortcut.
echo  * Enter name "flameshot" and command "/usr/bin/flameshot gui"
echo  * Set shortcut to PrtScr
