#!/usr/bin/env python3
""" Searches the SecLists default passwords for a match """

import os
import sys
import csv
from prettytable import PrettyTable

def main():
    if len(sys.argv) == 1:
        print("\nUsage: defaultcreds <search term>\nSearches on Vendor, Username and Password\n")
        sys.exit(1)

    search_term = sys.argv[1]
    search_results = PrettyTable()
    search_results.field_names = ["Vendor", "Username", "Password", "Comments"]

    password_file = "/usr/share/seclists/Passwords/Default-Credentials/default-passwords.csv"
    if os.path.exists(password_file):
        with open(password_file) as csv_file:
            csv_reader = csv.reader(csv_file, delimiter=',')
            for row in csv_reader:
                if search_term.lower() in [field.lower() for field in row]:
                    search_results.add_row([row[0], row[1], row[2], row[3][:80]])
            if len(search_results._rows) == 0:
                print("\nNo results. Try a google search?\n")
            else:
                print(search_results.get_string())
    else:
        print("\n\033[1;31m[!] \033[0;37mThe file 'default-passwords.csv' is not in the expected place (/usr/share/seclists/Passwords/Default-Credentials)\n")

if __name__ == "__main__":
    main()