#!/bin/bash

figlet skadi
ssh -t rafael@192.168.0.38 "sudo apt update && sudo apt upgrade -y"

figlet enso
ssh -t admin@52.63.243.88  "sudo apt update && sudo apt upgrade -y"

figlet xenon
ssh -t rafael@192.168.0.10 "/home/rafael/dotfiles/scripts/update-kali/update-kali"

figlet raiden
update-kali
