#!/bin/bash

# A maintenance script for Gentoo to automate cleaning/updating after
# a worldupdate

set -Eeuo pipefail
trap "echo -e \"\033[1;31m[!] \e[0mScript error occured in $0.\"" ERR

GREEN="\033[1;32m"
ENDCOLOUR="\033[0m"

echo -en $GREEN"\n>>> "$ENDCOLOUR
echo -e "Removing Unneeded Dependecides"
emerge --depclean

echo -en $GREEN"\n>>> "$ENDCOLOUR
echo -e "Rebuilding Broken Modules\n"
revdep-rebuild

echo -en $GREEN"\n>>> "$ENDCOLOUR
echo -e "Updating Config Files\n"
dispatch-conf

echo -en $GREEN"\n>>> "$ENDCOLOUR
echo -e "Checking World File\n"
emaint --check world

echo -en $GREEN"\n>>> "$ENDCOLOUR
echo -e "Rebuild Python Modules\n"
python-updater

echo -en $GREEN"\n>>> "$ENDCOLOUR
echo -e "Rebuild Perl Modules\n"
perl-cleaner --all
