#!/usr/bin/env python3

import time
from urllib.request import urlopen

URL = 'http://twitter.com'

def request_time():
    start_time = time.time()
    urlopen(URL).read()
    end_time = time.time()
    return end_time - start_time

def throttling_test(n):
    """Test if processing more than n requests is throttled."""
    experiment_start = time.time()
    for i in range(n):
        t = request_time()
        print ('Request #%d took %.5f ms' % (i+1, t * 1000.0))
    print ('--- Throttling limit crossed ---')

    t = request_time()
    print ('Request #%d took %.5f ms' % (n+1, t * 1000.0))

throttling_test(3)