#!/usr/bin/env python3
import os


def print_green(message):
    """ Prints a message to the console prefixed with a green '>>>' """
    print("\n\033[1;32;40m>>> \033[1;37;40m" + message + "\033[0;37;0m")

def gitupdate(directory):
    workingdir = os.getenv("HOME") + directory
    repos = os.listdir(workingdir)

    for repo in repos:
        print_green("Updating: " + repo)
        cmdstring = "git -C {}{} pull".format(workingdir, repo)
        os.system(cmdstring)
    return

if __name__ == "__main__":
    gitupdate('/.vim/bundle/')
    print ("")
